### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Platform' not found

### ISSUE THREAD

**Issue by joydashy** [jarnovanleeuwen/php-tikkie#5]
Hi there,

Trying to get this to work in a test script as follows:

`<?PHP
require __DIR__ . '/vendor/autoload.php';

use PHPTikkie\Environment;
use PHPTikkie\PHPTikkie;

$apiKey = "<key>";
$testMode = true;

$environment = new Environment($apiKey, $testMode);
$environment->loadPrivateKey('private_rsa.pem');

$tikkie = new PHPTikkie($environment);

$platform = $tikkie->newPlatform([
    // Mandatory attributes
    'name' => 'Carpool',
    'phoneNumber' => '<tel>',
    'platformUsage' => Platform::USAGE_TYPE_MYSELF,

    // Optional attributes
    'email' => 'email',
    'notificationUrl' => ''
])->save();

$platformToken = $platform->platformToken;

$user = $tikkie->newUser($platformToken, [
    'name' => '<name>',
    'phoneNumber' => '<tel>',
    'iban' => '<bank>',
    'bankAccountLabel' => 'ING'
])->save();

$userToken = $user->userToken;
$bankAccountToken = $user->bankAccounts[0]->bankAccountToken;

$paymentRequest = $tikkie->newPaymentRequest($platformToken, $userToken, $bankAccountToken, [
    // Mandatory attributes
    'amountInCents' => '1250',
    'currency' => 'EUR',
    'description' => 'Carpool'
])->save();

$tikkieUrl = $paymentRequest->paymentRequestUrl;
$paymentRequestToken = $paymentRequest->paymentRequestToken;

?>`

But then I get:

`PHP Fatal error:  Uncaught Error: Class 'Platform' not found in /home/redbull/carpool/test.php:19`

I am probably doing something wrong with Composer, not sure...

**Comment by jarnovanleeuwen** [comment]
You should import `Platform`:

```php
use PHPTikkie\Entities\Platform;
```

I have updated the readme.
