### ISSUE TITLE
Warning: file_get_contents(private_rsa.pem): ...

### ISSUE THREAD

**Issue by Theolodewijk** [jarnovanleeuwen/php-tikkie#7]
Warning: file_get_contents(private_rsa.pem): failed to open stream: No such file or directory in /home/***/domains/***.nl/vendor/jarnovanleeuwen/php-tikkie/src/Environment.php on line 65

```<?php

use PHPTikkie\Environment;
use PHPTikkie\PHPTikkie;

include $_SERVER['DOCUMENT_ROOT'] . '/../vendor/autoload.php';

$apiKey = "abc123";
$testMode = true;

$environment = new Environment($apiKey, $testMode);
$environment->loadPrivateKey('private_rsa.pem');

$tikkie = new PHPTikkie($environment);```

**Comment by jarnovanleeuwen** [comment]
Change `private_rsa.pem` to the absolute path of the file containing your private key. You can find more information about generating the public and private keys in the Tikkie API documentation.
